name: Update
on:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install packages
        run: python -m pip install -r requirements.txt
      - name: Run main
        run: python main.py
      - name: Dump database
        run: sqlite3 data.db .dump > data.sql
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Action update
